variable "project" {}
variable "az1" {}
variable "az2" {}
variable "vpc_cidr" {}
variable "subnet_dmz_cidr_az1" {}
variable "subnet_dmz_cidr_az2" {}
variable "subnet_priv_cidr_az1" {}
variable "subnet_priv_cidr_az2" {}
variable "flow_log_retention_in_days" {}
